version: '3'
services:
  foundryvtt:
    image: mcmillanator/foundryvtt:latest
    environment:
      - FOUNDRY_VTT_DATA_DIR=/data/foundryvtt
      - FOUNDRY_VTT_PORT=30000
    restart: always
    volumes:
      - foundryvtt_data:/data/foundryvtt
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:30000/"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - nginx

networks:
  nginx:
    external: true
volumes:
  foundryvtt_data:
