services:
  app:
    build:
      context: .
    image: mcmillanator/gemstash
    hostname: gemstash
    restart: always
    volumes:
      - gemstash:/home/.gemstash
    networks:
      - nginx

volumes:
  gemstash:

networks:
  nginx:
    external: true
