version: '3'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx-data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - nginx

networks:
  nginx:
    external: true
volumes:
  nginx-data:
  letsencrypt:
