version: '3'
services:
  minecraft:
    container_name: minecraft
    image: mcmillanator/minecraft
    restart: unless-stopped
    networks:
      - nginx 
    volumes:
      - minecraft:/minecraft

networks:
  nginx:
    external: true
volumes:
  minecraft:
