version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  app:
    container_name: pihole
    hostname: pi-hole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 8000:80
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: tintree73
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)  
    networks:
      pihole_network:
        ipv4_address: 172.25.0.10
      docker_default:


networks:
  docker_default:
    external: true
  pihole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
