---
version: "2.1"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: StanPlexServer
    #user: plex
    ports:
    #network_mode: host
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - TZ="America/New_York"
      - ADVERTISE_IP="http://192.168.1.2:32400/"
    volumes:
      - /mnt/PlexServer/config:/config
      - /mnt/PlexServer/movies:/movies
      - /mnt/PlexServer/music:/music
      - /mnt/PlexServer/tv:/tv
    restart: unless-stopped
